# Generated by Django 4.2.6 on 2023-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_img1_alter_item_img2_alter_item_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.CharField(max_length=150),
        ),
    ]
